### ISSUE TITLE
Is this library updated to last version ? 

### ISSUE THREAD

**Issue by cristea2017** [ZtechNetwork/MCBVanillaBehaviorPack#1]
Hi !  have you updated behavior pack to last update :

[https://feedback.minecraft.net/hc/en-us/articles/360046901272-Minecraft-1-16-20-Bedrock-](url)
 
You can find resource here :
[https://minecraft.gamepedia.com/Add-on](url)    in Templates Section

**Comment by LeronHinds** [comment]
Sorry for the really late response. I will be working in the next week or so to updating the repositories. I've been caught up with college stuff lately so I will update it as soon as I can.
