### ISSUE TITLE
Many mobs entity files are missing

### ISSUE THREAD

**Issue by faradey8951** [ZtechNetwork/MCBVanillaBehaviorPack#2]
Can't find piglin, piglin brute, bee etc. entity files in 1.16.20 release

**Comment by LeronHinds** [comment]
Sorry about that, I will update this repository as soon as I can with that. This was provided directly from the game files of v1.16.20-40 so I'm not sure why some mobs got removed in the process. Thanks for reporting this!

**Comment by erik1988** [comment]
Thank you for making this available. Would you mind sharing how you are able to get this from the game files? I just wanted to have a peak and see if there are any json files for blocks in the new beta version of the game. Thanks.

**Comment by LeronHinds** [comment]
I just added all of the missing entity files in the latest commit d4160cb. A [release](https://github.com/ZtechNetwork/MCBVanillaBehaviorPack/releases) will be available shortly.
